### ISSUE TITLE
Blocking input functions allow the pygame event queue to fill and block forever

### ISSUE THREAD

**Issue by schilcote** [asweigart/pygcurse#19]
The title just about says it all, really. If you run a program that calls `pygcurse.event()` or `pygcurse.PygcurseSurface.input()`, alt-tab away, do some other things, and then alt-tab back, the program will have ceased responding to input 'cos Pygame's event buffer has filled.

My pull request addresses this by allowing the `get()` calls within these functions to pull out all events (nothing else was gonna use them) instead of just the interesting ones. I have confirmed that the fix works.

**Comment by asweigart** [comment]
Accepted the PR. Thanks!
