### ISSUE TITLE
Importing pygcurse causes error [Python 3.4]

### ISSUE THREAD

**Issue by SergioAC** [asweigart/pygcurse#22]
It gives this error:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import pygcurse
  File "C:\Python34\lib\site-packages\pygcurse\__init__.py", line 79, in <module>
    colornames[cname] = pygame.Color(cname)
ValueError: invalid color name

I'm using the 32-bit version of Python 3.4. I istalled pygcurse using pip version 7.0.3 and my pygame version is 1.9.2a0.

**Comment by schilcote** [comment]
My pull request fixes this.
https://github.com/asweigart/pygcurse/pull/23

**Comment by asweigart** [comment]
Thank you very much for reaching out to me. I have no clue how long this hasn't worked. :P

I wrote Pygcurse over the course of a couple weeks, but didn't make unit tests for it. Hopefully I'll have time to get back to it in the next few months sometime.

THANKS!
